# Generated by Django 5.2.1 on 2025-06-04 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='professore',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.professore'),
        ),
    ]
