# Generated by Django 5.2.1 on 2025-06-06 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_professore_student_professore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='professore',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='professore_students', to='students.professore'),
        ),
    ]
