# Generated by Django 5.2.1 on 2025-06-06 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_professore'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChessCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50)),
                ('course_price', models.IntegerField()),
                ('professor_rate', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='students_course',
            field=models.ManyToManyField(related_name='course_students', to='students.chesscourse'),
        ),
    ]
