# Generated by Django 5.2.1 on 2025-06-06 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_chesscourse_student_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='students_course',
            field=models.ManyToManyField(null=True, related_name='course_students', to='students.chesscourse'),
        ),
    ]
