# Generated by Django 5.2.1 on 2025-06-06 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_student_students_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='students_course',
            field=models.ManyToManyField(related_name='course_students', to='students.chesscourse'),
        ),
    ]
