# Generated by Django 5.2.1 on 2025-06-09 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_student_students_course'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Professore',
            new_name='Professor',
        ),
        migrations.RemoveField(
            model_name='student',
            name='professore',
        ),
        migrations.AddField(
            model_name='student',
            name='professor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='professor_students', to='students.professor'),
        ),
    ]
