# Generated by Django 4.2.23 on 2025-06-12 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_rename_professore_professor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='students_course',
            new_name='students_courses',
        ),
    ]
