# Generated by Django 4.2.23 on 2025-06-14 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_student_lesson_in_month_student_per_lesson'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='lesson_in_month',
            new_name='lessons_in_month',
        ),
    ]
