# Generated by Django 4.2.23 on 2025-06-14 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_rename_lesson_in_month_student_lessons_in_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='per_lesson',
        ),
        migrations.AddField(
            model_name='chesscourse',
            name='per_lesson',
            field=models.BooleanField(default=False),
        ),
    ]
