# Generated by Django 4.2.23 on 2025-06-14 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_remove_student_per_lesson_chesscourse_per_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='lessons_in_month',
        ),
        migrations.AddField(
            model_name='chesscourse',
            name='lessons_in_month',
            field=models.IntegerField(null=True),
        ),
    ]
