# Generated by Django 4.2.23 on 2025-06-14 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_remove_student_lessons_in_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chesscourse',
            name='lessons_in_month',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
