# Generated by Django 4.2.23 on 2025-06-18 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_alter_chesscourse_lessons_in_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='picture',
            field=models.ImageField(null=True, upload_to='professors_pics/'),
        ),
    ]
