# Generated by Django 4.2.23 on 2025-06-19 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_professor_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='notations',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
