# Generated by Django 4.2.23 on 2025-06-19 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_student_notations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='notations',
            field=models.TextField(default='Поки-що немає нотатків', max_length=1000),
        ),
    ]
